// Phase 0.5 — consultation priorities: computation → session state → hf2
// Consultation Summary → email payload projection.
//
// This does NOT grep for behavior. It EXTRACTS the real showProfileScreen(),
// renderResultsTrialFocus(), renderHf2Priorities(), L(), escapeHtml() and the
// payload's priorities projection from index.html and EXECUTES them against a
// recording DOM shim — the same extract-and-execute pattern as
// tests/session_safety_check.mjs and tests/data_error_recovery_check.mjs.
//
// The Sleep Brief pin: tests/fixtures/sleep_brief_baseline_572d405.json was
// generated by executing the PRE-0.5 showProfileScreen (commit 572d405, the
// baseline main this phase branched from) against the fixtures below. The
// current tree must reproduce that recorded output byte-identically — the
// priorities block, summary, heading/intro, reflection, reassurance, meta
// strip, journey block, secondary/CTA, profileBriefByLang and the results
// trial-focus derivative: every element that render writes. (One recorded
// exception: the CTA label's fourteen "cta" fields — see the 2026-08-10
// amendment at the regeneration ratchet below.) That is what
// "0.5 does not change the Sleep Brief" means, made executable. Do NOT
// regenerate that file from a post-0.5 tree; a regenerated pin certifies
// whatever the change produced, which is the vacuity this suite exists to
// prevent.
//
// Fixture design (derived by executing the real engine at 572d405):
//   C — sorted top-3 is a DIFFERENT SET from its insertion top-3, so it kills
//       "sort removed", "sort reversed" and "slice before sort" at once. It
//       also carries a real tie (Motion control 90 vs Consistent support 90)
//       resolved by stable-sort insertion order.
//   E, F — different populated orders; F's three are all kind:'compare'.
//   A — the classic hot side sleeper.
//   I — a tie at rank 1–2 (two 100s), pinning tie stability.
//   B — exactly TWO priorities; H — exactly ONE. The engine produces 1–3, not
//       always three; both surfaces must render the engine's count, never pad.
// A "sorted order == insertion order" fixture is deliberately ABSENT from the
// order tests: on such a fixture every order mutation survives.
//
// Run: node tests/consultation_priorities_check.mjs

import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const html = readFileSync(join(root, "index.html"), "utf8");
const BASELINE_RAW = readFileSync(
  join(root, "tests", "fixtures", "sleep_brief_baseline_572d405.json"));
const BASELINE = JSON.parse(BASELINE_RAW.toString("utf8"));
// Slice 2 moved the Sleep Brief's chrome copy into the governed dictionaries,
// so the harness resolves t() against the real ones instead of echoing keys.
const DICTS = {
  en: JSON.parse(readFileSync(join(root, "data", "dict-en.json"), "utf8")),
  es: JSON.parse(readFileSync(join(root, "data", "dict-es.json"), "utf8")),
};

// THE REGENERATION RATCHET. Nothing mechanical can stop a commit regenerating
// the fixture from changed code — but pinning its hash HERE means doing so
// requires editing two files, one of which is this comment telling the editor
// that a regenerated pin certifies whatever the change produced. An audit
// demonstrated the silent single-file regeneration end to end; this is the
// answer. If the Sleep Brief legitimately changes in a later phase, the new
// baseline must be generated from the PRE-change commit of THAT phase, and
// this hash updated in the same reviewed diff.
//
// 2026-08-10 amendment (owner-authorized Sleep Brief CTA relabel): the
// fixture's fourteen "cta" fields — and ONLY those fields — were hand-edited
// to the ruled pair ("See My Matches →" / "Ver Mis Opciones →"), not
// regenerated; every other byte remains the executed 572d405 output, and this
// hash moved in the same reviewed diff. The final section below pins the
// ruled pair as literals, so the fixture and the source must agree with the
// ruling independently — a regeneration cannot move the label silently.
// 2026-08-23 amendment (owner-authorized Sleep Brief copy change, Slice 5
// C10): the "Comfortable elevation" testing prose — "Try the finalist flat,
// ..." / "Prueba el finalista plano ..." — was hand-edited to "Try the mattress
// flat, ..." / "Prueba el colchón plano ..." in its eight occurrences (the four
// `test` fields and the four `prioritiesHtml` strings of fixtures C and I,
// EN and ES), not regenerated; every other byte remains the executed 572d405
// output, and this hash moved in the same reviewed diff. The final section
// pins the ruled wording as literals so fixture and source must agree with the
// ruling independently.
const BASELINE_SHA256 = "0dbd354c2fb7e64237e18f1c7b75a0cd5795f980e9ae1c58a6ba4d1e835170c4";

let passed = 0, failed = 0;
function check(label, cond) {
  if (cond) { passed++; console.log(`  [ok] ${label}`); }
  else { failed++; console.log(`  [FAIL] ${label}`); }
}
function section(name) { console.log(`\n-- ${name} --`); }
function grab(re, what) {
  const m = html.match(re);
  check(`extracted ${what}`, !!m);
  return m ? m[0] : "";
}

section("the baseline fixture is the reviewed one");
// Hashed over LF-normalized text, so the pin survives git's CRLF smudge on
// a fresh Windows checkout.
check("sleep_brief_baseline_572d405.json matches its pinned sha256",
  createHash("sha256")
    .update(BASELINE_RAW.toString("utf8").split("\r\n").join("\n"))
    .digest("hex") === BASELINE_SHA256);

// ---------- extractions ------------------------------------------------------
section("extraction");
const PROFILE_FN = grab(/function showProfileScreen\(\) \{[\s\S]*?\r?\n    \}\r?\n/, "showProfileScreen()");
const SIGNATURE_FN = grab(/function buildSleepSignatureSvg\(answers\) \{[\s\S]*?\r?\n    \}/, "buildSleepSignatureSvg()");
const TRIAL_FN = grab(/function renderResultsTrialFocus\(\)\s*\{[\s\S]*?\n    \}/, "renderResultsTrialFocus()");
const HF2_FN = grab(/function renderHf2Priorities\(\)\s*\{[\s\S]*?\n    \}/, "renderHf2Priorities()");
const L_FN = grab(/function L\(obj\) \{[\s\S]*?\n    \}/, "L()");
const ESCAPE_FN = grab(/function escapeHtml\([\s\S]*?\n    \}/, "escapeHtml()");
const PROJECTION = grab(
  /priorities: \(Array\.isArray\(analytics\.trialFocus\) \? analytics\.trialFocus : \[\]\)[\s\S]*?\.filter\(function\(p\) \{ return p\.name; \}\),/,
  "the payload priorities projection");

// ---------- fixtures (identical to the baseline generator's) ----------------
const FIXTURES = {
  C: { sleep_position: "combo", temperature: "cold", firmness: 2,
       partner_sleep: "family", partner_disturbance: "sometimes",
       sleep_issues: ["hip_pain", "sagging"], health_conditions: ["reflux"],
       body_type: "plus", mattress_size: "queen" },
  E: { sleep_position: "stomach", temperature: "cold", firmness: 8,
       partner_sleep: "partner", partner_disturbance: "yes_often",
       sleep_issues: ["sagging"], health_conditions: [], mattress_size: "king" },
  F: { sleep_position: "combo", temperature: "opposite", firmness: 2,
       partner_sleep: "partner", partner_disturbance: "no",
       sleep_issues: [], health_conditions: ["allergies"], mattress_size: "full" },
  A: { sleep_position: "side", temperature: "hot", firmness: 4,
       partner_sleep: "partner", partner_disturbance: "yes_often",
       sleep_issues: ["back_pain", "hot"], health_conditions: ["snoring"], mattress_size: "queen" },
  I: { sleep_position: "back", temperature: "hot", firmness: 6,
       partner_sleep: "partner", partner_disturbance: "sometimes",
       sleep_issues: ["back_pain"], health_conditions: ["snoring"],
       body_type: "plus", mattress_size: "twin" },
  B: { sleep_position: "back", temperature: "comfortable", firmness: 8,
       partner_sleep: "solo", sleep_issues: ["none"], health_conditions: ["none"],
       mattress_size: "twin_xl" },
  H: {},
};
const ORDER_FIXTURES = ["C", "E", "F", "A", "I"];   // never B/H — bounds only

// ---------- harness ----------------------------------------------------------
function makeDoc() {
  const els = new Map();
  const make = (id) => {
    const classes = new Set();
    return {
      id, innerHTML: "", textContent: "", style: {},
      classList: {
        add: (c) => classes.add(c),
        remove: (c) => classes.delete(c),
        contains: (c) => classes.has(c),
      },
      setAttribute() {}, getAttribute: () => null, focus() {},
    };
  };
  const doc = {
    getElementById: (id) => {
      if (!els.has(id)) els.set(id, make(id));
      return els.get(id);
    },
    querySelector: () => null, querySelectorAll: () => [],
  };
  return { els, doc };
}

// Executes the real profile render (and the results derivative) for one
// fixture in one language. Returns the recorded DOM plus the analytics state.
function runProfile(fixture, lang) {
  const { els, doc } = makeDoc();
  const analytics = { trialFocus: [], log() {} };
  const out = {};
  const dict = DICTS[lang] || DICTS.en;
  new Function("document", "window", "answers", "currentLang", "analytics", "out", "dict",
    `"use strict";
    function t(k) { return Object.prototype.hasOwnProperty.call(dict, k) ? dict[k] : k; }
    function showScreen() {}
    function dfmReducedMotion() { return false; }
    var _briefOpenPriority = null;
    ${ESCAPE_FN}
    ${L_FN}
    ${SIGNATURE_FN}
    ${PROFILE_FN}
    ${TRIAL_FN}
    out.run = function() { showProfileScreen(); renderResultsTrialFocus(); };
    `)(doc, {}, JSON.parse(JSON.stringify(fixture)), lang, analytics, out, dict);
  out.run();
  return { els, analytics };
}

// Parses the Slice 2 disclosure accordion. `title` is the toggle's visible
// (and accessible) name; `why` and `test` are the prose inside the panel —
// the same three strings the 572d405 rows carried as title/desc/test, which
// is what lets that fixture keep working as a semantic oracle.
function parseBriefList(innerHTML) {
  return [...innerHTML.matchAll(/<li class="noct-profile-priority-row">([\s\S]*?)<\/li>/g)]
    .map((m) => ({
      title: (m[1].match(/priority-title">([\s\S]*?)<\/span>/) || [, ""])[1],
      why: (m[1].match(/priority-why">([\s\S]*?)<\/p>/) || [, ""])[1],
      test: (m[1].match(/priority-test"><strong>[\s\S]*?<\/strong>([\s\S]*?)<\/p>/) || [, ""])[1],
    }));
}

// Executes the real hf2 renderer against a stored trialFocus state.
function runHf2(trialFocus, lang) {
  const { els, doc } = makeDoc();
  const analytics = { trialFocus };
  const out = {};
  new Function("document", "currentLang", "analytics", "out",
    `"use strict";
    ${ESCAPE_FN}
    ${L_FN}
    ${HF2_FN}
    out.run = function() { renderHf2Priorities(); };
    `)(doc, lang, analytics, out);
  out.run();
  return {
    section: els.get("hf2PrioritiesSection"),
    list: els.get("hf2Priorities"),
    names: [...els.get("hf2Priorities").innerHTML.matchAll(/<strong>([\s\S]*?)<\/strong>/g)]
      .map((m) => m[1]),
  };
}

// Executes the real payload projection expression, exactly as extracted.
function runProjection(trialFocus, lang) {
  return new Function("analytics", "currentLang",
    `"use strict";
    return { ${PROJECTION} }.priorities;`)({ trialFocus }, lang);
}

// ===========================================================================
// 1. COMPUTATION AND ORDER — the engine's output, per fixture, per language
// ===========================================================================
section("computation: engine order, count and tie stability");
for (const f of ORDER_FIXTURES) {
  for (const lang of ["en", "es"]) {
    const { analytics } = runProfile(FIXTURES[f], lang);
    const got = analytics.trialFocus.map((t) => t[lang]);
    const want = BASELINE[f][lang].trialFocus.map((t) => t[lang]);
    check(`[${f}/${lang}] engine order pinned: ${want.join(" > ")}`,
      JSON.stringify(got) === JSON.stringify(want));
  }
}
{
  const b = runProfile(FIXTURES.B, "en").analytics.trialFocus;
  const h = runProfile(FIXTURES.H, "en").analytics.trialFocus;
  check("the engine produces TWO priorities for fixture B — never padded to three",
    b.length === 2);
  check("...and ONE for fixture H", h.length === 1);
}

// ===========================================================================
// 2. SLEEP BRIEF UNCHANGED — executed output vs the 572d405 pin
// ===========================================================================
// Slice 2 (D1 recomposition, owner-authorized 2026-08-15) changed this
// screen's STRUCTURE. The fixture and its sha are deliberately UNCHANGED:
// regenerating a DOM golden from the very code under review would have made
// the strongest Sleep Brief pin certify whatever the slice produced. Instead
// the 572d405 bytes keep working as the HISTORICAL SEMANTIC ORACLE — the
// customer-facing meaning that must survive any recomposition — while the new
// D1 structural and behavioral contract is owned by
// tests/sleep_brief_presentation_check.mjs.
//
// Surviving, still pinned here: the priority set/order and all three strings
// per row, the reflection sentence, the heading/intro/plan label, the stored
// brief and trial-focus state, the Results derivative, and both buttons.
// Deliberately NOT pinned: the removed surfaces (subtitle line, summary line,
// meta strip, reassurance, journey rail, category tags) and the raw
// innerHTML shape, which the recomposition rewrote by ruling. The subtitle
// keeps its pin as ANALYTICS state — the ruling removed it from the DOM while
// preserving its computation, and this is what proves that.
section("Sleep Brief semantics survive the D1 recomposition (572d405 oracle)");
for (const f of Object.keys(FIXTURES)) {
  for (const lang of ["en", "es"]) {
    const { els, analytics } = runProfile(FIXTURES[f], lang);
    const pin = BASELINE[f][lang];
    const got = parseBriefList(els.get("profilePriorities").innerHTML);
    const oracle = pin.priorities.map((p) => ({ title: p.title, why: p.desc, test: p.test }));
    check(`[${f}/${lang}] priority titles, reasons and testing prose unchanged`,
      JSON.stringify(got) === JSON.stringify(oracle));
    check(`[${f}/${lang}] row count unchanged`, got.length === pin.priorities.length);
    check(`[${f}/${lang}] heading and intro unchanged`,
      els.get("profilePrioritiesHeading").textContent === pin.heading
      && els.get("profilePrioritiesIntro").textContent === pin.intro);
    check(`[${f}/${lang}] profileBriefByLang unchanged (both languages)`,
      JSON.stringify(analytics.profileBriefByLang) === JSON.stringify(pin.briefByLang));
    check(`[${f}/${lang}] results trial-focus derivative unchanged`,
      els.get("resultsTrialFocus").innerHTML === pin.resultsTrialFocus);
    check(`[${f}/${lang}] retained screen copy unchanged (heading, reflection, plan label, both buttons)`,
      els.get("profileName").textContent === pin.profileName
      && els.get("profileReflection").textContent === pin.reflection
      && els.get("profilePlanLabel").textContent === pin.planLabel
      && els.get("profileSecondary").textContent === pin.secondary
      && (els.get("profileCta").innerHTML || els.get("profileCta").textContent) === pin.cta);
    // The ruling removed the subtitle from the customer-visible DOM and
    // PRESERVED its computation, analytics fields and email fallback. The
    // oracle proves the computation is byte-for-byte the historical one.
    check(`[${f}/${lang}] subtitle computation preserved in analytics (removed from the DOM only)`,
      analytics.profileSubtitle === pin.subtitle
      && analytics.profileSubtitleByLang[lang] === pin.subtitle);
    // The pin's trialFocus carried only {en, es}; the widened state must still
    // agree on those names, in the same positions.
    check(`[${f}/${lang}] trialFocus name pairs unchanged`,
      JSON.stringify(analytics.trialFocus.map((t) => ({ en: t.en, es: t.es })))
      === JSON.stringify(pin.trialFocus));
  }
}

// ===========================================================================
// 2b. THE RESULTS DERIVATIVE'S VISIBILITY SEMANTICS
// ===========================================================================
// The innerHTML pin cannot see classList, and the old no-op shim hid a real
// property: the strip must carry is-visible exactly when there is content.
section("results trial-focus visibility classes");
{
  const withContent = runProfile(FIXTURES.C, "en");
  check("with priorities, the strip carries is-visible",
    withContent.els.get("resultsTrialFocus").classList.contains("is-visible"));
  // Empty store: execute the real derivative alone against no content.
  const { els, doc } = makeDoc();
  els.set === undefined; // (no-op; keep shape)
  const out = {};
  new Function("document", "currentLang", "analytics", "out",
    `"use strict";
    ${ESCAPE_FN}
    ${L_FN}
    ${TRIAL_FN}
    out.run = function() { renderResultsTrialFocus(); };
    `)(doc, "en", { trialFocus: [] }, out);
  doc.getElementById("resultsTrialFocus").classList.add("is-visible"); // stale
  doc.getElementById("resultsTrialFocus").innerHTML = "stale";
  out.run();
  check("with an empty store, the strip is emptied AND is-visible is removed",
    doc.getElementById("resultsTrialFocus").innerHTML === ""
    && !doc.getElementById("resultsTrialFocus").classList.contains("is-visible"));
}

// ===========================================================================
// 3. THE WIDENED STATE
// ===========================================================================
section("the widened session state: bilingual prose, nothing internal");
{
  const { analytics } = runProfile(FIXTURES.C, "en");
  const KEYS = ["en", "es", "test", "why"];
  analytics.trialFocus.forEach((item, i) => {
    check(`element ${i}: key set is exactly en/es/why/test — no score, kind or rank`,
      JSON.stringify(Object.keys(item).sort()) === JSON.stringify(KEYS));
    check(`element ${i}: why and test are bilingual pairs`,
      typeof item.why.en === "string" && item.why.en.length > 0
      && typeof item.why.es === "string" && item.why.es.length > 0
      && typeof item.test.en === "string" && item.test.en.length > 0
      && typeof item.test.es === "string" && item.test.es.length > 0);
    check(`element ${i}: the ES prose is actually Spanish, not a copied EN string`,
      item.why.en !== item.why.es && item.test.en !== item.test.es);
  });
  // Language-independence of the STORE: computing under ES yields the same
  // bilingual state as computing under EN.
  const esState = runProfile(FIXTURES.C, "es").analytics.trialFocus;
  check("the stored state is identical whichever language computed it",
    JSON.stringify(esState) === JSON.stringify(analytics.trialFocus));
}

// ===========================================================================
// 4. THE CONSULTATION SUMMARY RENDER
// ===========================================================================
section("hf2: ordered render from stored state, both languages, no recompute");
{
  const state = runProfile(FIXTURES.C, "en").analytics.trialFocus;
  const en = runHf2(state, "en");
  check("visible with valid state", en.section.style.display === "");
  check("renders every stored priority, in order",
    JSON.stringify(en.names) === JSON.stringify(state.map((t) => t.en)));
  check("the renderer writes <li> only — the <ol> itself stays the static one",
    !/<ol/.test(en.list.innerHTML) && /^<li /.test(en.list.innerHTML));
  check("each row carries the reason and the testing prompt",
    state.every((t) => en.list.innerHTML.includes(t.why.en))
    && state.every((t) => en.list.innerHTML.includes(t.test.en)));
  check("the EN render uses the EN testing label", en.list.innerHTML.includes("Try this: ")
    && !en.list.innerHTML.includes("Pruébalo: "));

  const es = runHf2(state, "es");
  check("the SAME stored state renders Spanish",
    JSON.stringify(es.names) === JSON.stringify(state.map((t) => t.es)));
  check("the ES render uses the ES testing label", es.list.innerHTML.includes("Pruébalo: ")
    && !es.list.innerHTML.includes("Try this: "));
  // Cross-language leakage, both directions, all three fields.
  check("no Spanish leaks into the EN render",
    state.every((t) => !en.list.innerHTML.includes(t.es))
    && state.every((t) => !en.list.innerHTML.includes(t.why.es)));
  check("no English leaks into the ES render",
    state.every((t) => !es.list.innerHTML.includes(t.en))
    && state.every((t) => !es.list.innerHTML.includes(t.why.en)));
  // Positional correspondence: EN[i] and ES[i] are two halves of ONE pair —
  // the assertion that catches any per-language re-sort or name-keyed tiebreak.
  check("EN and ES renders correspond position by position",
    en.names.every((n, i) => state[i].en === n && es.names[i] === state[i].es));
}
{
  // The poison proof: the render must come from the STORE, not from answers.
  // Fixture E is a different POPULATED order — a renderer that recomputes from
  // answers produces E's sequence, visibly, where {} would look like "empty".
  const state = runProfile(FIXTURES.C, "en").analytics.trialFocus;
  const eNames = runProfile(FIXTURES.E, "en").analytics.trialFocus.map((t) => t.en);
  const got = runHf2(state, "en").names;
  check("rendering C's stored state can never produce E's order (no recompute path)",
    JSON.stringify(got) !== JSON.stringify(eNames)
    && JSON.stringify(got) === JSON.stringify(state.map((t) => t.en)));
  check("renderHf2Priorities reads nothing outside the store — no answers, no window, no engine",
    !/\banswers\b|\bwindow\b|\bshowProfileScreen\b|\bcalculateScores\b/.test(HF2_FN));
  // The behavioral backstop: the render harness binds NO window and NO
  // answers, so any genuine recompute path that survives the grep throws a
  // ReferenceError under "use strict" and the suite goes red by crash.
  check("the render harness really does bind neither window nor answers", true);
}
{
  // Bounds and emptiness: 2-priority and 1-priority states render at length.
  const b = runProfile(FIXTURES.B, "en").analytics.trialFocus;
  check("a 2-priority state renders exactly 2 rows", runHf2(b, "en").names.length === 2);
  const h = runProfile(FIXTURES.H, "en").analytics.trialFocus;
  check("a 1-priority state renders exactly 1 row", runHf2(h, "en").names.length === 1);

  // Missing/invalid state hides the WHOLE section and empties the list.
  // Each case starts from a SEEDED, VISIBLE render in one persistent harness —
  // a fresh shim's list starts empty, so asserting emptiness there proves
  // nothing (the vacuity an audit confirmed on the fresh-harness version).
  for (const [label, bad] of [
    ["an empty array", []],
    ["a wiped (undefined) field", undefined],
    ["a pre-widening shape (names only, no prose)", [{ en: "X", es: "Y" }]],
    ["entries missing the test prompt", [{ en: "X", es: "Y", why: { en: "w", es: "w2" } }]],
  ]) {
    const { els, doc } = makeDoc();
    const analytics = { trialFocus: runProfile(FIXTURES.C, "en").analytics.trialFocus };
    const out = {};
    new Function("document", "currentLang", "analytics", "out",
      `"use strict";
      ${ESCAPE_FN}
      ${L_FN}
      ${HF2_FN}
      out.run = function() { renderHf2Priorities(); };
      `)(doc, "en", analytics, out);
    out.run();
    check(`[${label}] precondition: visible with content first`,
      els.get("hf2PrioritiesSection").style.display === ""
      && els.get("hf2Priorities").innerHTML.length > 0);
    analytics.trialFocus = bad;
    out.run();
    check(`${label} hides the section entirely and empties the list`,
      els.get("hf2PrioritiesSection").style.display === "none"
      && els.get("hf2Priorities").innerHTML === "");
  }
  // Slice 5 C0 — MIXED VALIDITY (owner ruling R-8, 2026-08-21). The hostile
  // fixtures above test the two ENDS of the validity spectrum (all valid, all
  // invalid). The middle was never exercised: three stored entries with ONE
  // malformed. The governing contract (roadmap 0.5: "render the engine's count
  // in the engine's order — never padded, never synthesised"; Phase 1
  // constraint 2: never "filter ... elements") admits no partial render, and the
  // owner ruled ALL-OR-NOTHING FAIL-CLOSED: any malformed entry invalidates the
  // whole collection; never filter, shorten, pad, synthesise or partially
  // render. This block is RED at 4a76503 by design (the renderer filters per
  // element and emits 2 rows) and is repaired in the prerequisite commit.
  for (const badIndex of [0, 1, 2]) {
    for (const lang of ["en", "es"]) {
      const { els, doc } = makeDoc();
      const base = runProfile(FIXTURES.C, lang).analytics.trialFocus;
      if (base.length !== 3) { check(`[mixed] fixture C yields 3 priorities in ${lang} (got ${base.length})`, false); continue; }
      const analytics = { trialFocus: base };
      const out = {};
      new Function("document", "currentLang", "analytics", "out",
        `"use strict";
        ${ESCAPE_FN}
        ${L_FN}
        ${HF2_FN}
        out.run = function() { renderHf2Priorities(); };
        `)(doc, lang, analytics, out);
      out.run();
      check(`[mixed ${lang} idx${badIndex}] precondition: all-valid renders exactly 3 rows`,
        (els.get("hf2Priorities").innerHTML.match(/<li /g) || []).length === 3);
      const broken = Object.assign({}, base[badIndex]);
      delete broken.test;
      analytics.trialFocus = base.map((x, i) => (i === badIndex ? broken : x));
      out.run();
      const rows = (els.get("hf2Priorities").innerHTML.match(/<li /g) || []).length;
      const hidden = els.get("hf2PrioritiesSection").style.display === "none";
      check(`[mixed ${lang} idx${badIndex}] one malformed entry is ALL-OR-NOTHING: the section hides and the list empties — never a silent partial (rows=${rows} hidden=${hidden})`,
        rows === 0 && hidden && els.get("hf2Priorities").innerHTML === "");
      // Negative control: restoring the full valid array restores all 3.
      analytics.trialFocus = base;
      out.run();
      check(`[mixed ${lang} idx${badIndex}] negative control: the restored valid array renders 3 rows again`,
        (els.get("hf2Priorities").innerHTML.match(/<li /g) || []).length === 3
        && els.get("hf2PrioritiesSection").style.display === "");
    }
  }
  // EN and ES must agree on the count from identical stored state: a
  // language-dependent partial is a second way to ship a shortened list.
  {
    const mk = (lang) => {
      const { els, doc } = makeDoc();
      const base = runProfile(FIXTURES.C, lang).analytics.trialFocus;
      const broken = Object.assign({}, base[1]); delete broken.why;
      const analytics = { trialFocus: [base[0], broken, base[2]] };
      new Function("document", "currentLang", "analytics",
        `"use strict"; ${ESCAPE_FN} ${L_FN} ${HF2_FN} renderHf2Priorities();`)(doc, lang, analytics);
      return (els.get("hf2Priorities").innerHTML.match(/<li /g) || []).length;
    };
    const en = mk("en"), es = mk("es");
    check(`[mixed] EN and ES render the SAME count from the same partially-malformed state (en=${en}, es=${es}) and that count is 0`,
      en === es && en === 0);
  }

  // The hide is not the vacuous starting state: show first, then clear.
  const state = runProfile(FIXTURES.C, "en").analytics.trialFocus;
  const { els, doc } = makeDoc();
  const analytics = { trialFocus: state };
  const out = {};
  new Function("document", "analytics", "out", "langBox",
    `"use strict";
    var currentLang = 'en';
    ${ESCAPE_FN}
    ${L_FN}
    ${HF2_FN}
    out.run = function() { renderHf2Priorities(); };
    `)(doc, analytics, out, {});
  out.run();
  check("precondition: rendered visible with 3 rows first",
    els.get("hf2PrioritiesSection").style.display === ""
    && (els.get("hf2Priorities").innerHTML.match(/<li /g) || []).length === 3);
  analytics.trialFocus = [];
  out.run();
  check("REGRESSION: clearing the state hides the section and empties the list",
    els.get("hf2PrioritiesSection").style.display === "none"
    && els.get("hf2Priorities").innerHTML === "");
}
{
  // Hostile copy cannot become markup — proven PER FIELD, each with its own
  // angle-bracket payload, so removing the escape at any single interpolation
  // fails its own named assertion (an audit showed the test field's escape
  // was removable when only name and why carried brackets).
  for (const field of ["name", "why", "test"]) {
    const entry = { en: "Safe name", es: "Safe",
      why: { en: "safe why", es: "w" }, test: { en: "safe test", es: "t" } };
    const payload = '<script>alert(1)</script><img src=x onerror=y>';
    if (field === "name") { entry.en = payload; }
    else entry[field] = { en: payload, es: "x" };
    const r = runHf2([entry], "en");
    check(`hostile ${field}: no live tag in the hf2 render`,
      !r.list.innerHTML.includes("<script>") && !r.list.innerHTML.includes("<img ")
      && r.list.innerHTML.includes("&lt;script&gt;"));
  }
}

// ===========================================================================
// 5. THE PAYLOAD PROJECTION
// ===========================================================================
section("payload: bounded, allowlisted, pre-localized, ordered");
{
  const state = runProfile(FIXTURES.C, "en").analytics.trialFocus;
  for (const lang of ["en", "es"]) {
    const p = runProjection(state, lang);
    check(`[${lang}] three entries for a three-priority state`, p.length === 3);
    p.forEach((e, i) => {
      check(`[${lang}] entry ${i}: key set is exactly name/reason/test`,
        JSON.stringify(Object.keys(e).sort()) === JSON.stringify(["name", "reason", "test"]));
      check(`[${lang}] entry ${i}: every value is a non-empty string`,
        [e.name, e.reason, e.test].every((v) => typeof v === "string" && v.length > 0));
    });
    check(`[${lang}] order matches the stored order`,
      JSON.stringify(p.map((e) => e.name))
      === JSON.stringify(state.map((t) => t[lang])));
    check(`[${lang}] prose is pre-localized to ${lang}`,
      p.every((e, i) => e.reason === state[i].why[lang] && e.test === state[i].test[lang]));
  }
  // Nothing internal survives the projection.
  const blob = JSON.stringify(runProjection(state, "en"));
  check("no internal marker in the payload field",
    !/"(score|kind|rank|id|en|es|why)":/.test(blob));
  // Raw answer ids never appear in customer copy, so any hit is a leak.
  for (const raw of ["hip_pain", "yes_often", "back_pain", "cal_king", "sagging"]) {
    check(`no raw answer id "${raw}" in the payload field`, !blob.includes(raw));
  }
  check("the projection returns fresh objects, not references into the store",
    runProjection(state, "en")[0] !== state[0]);
}
{
  const b = runProfile(FIXTURES.B, "en").analytics.trialFocus;
  check("a 2-priority state ships 2 entries — never padded",
    runProjection(b, "en").length === 2);
  const h = runProfile(FIXTURES.H, "en").analytics.trialFocus;
  check("a 1-priority state ships 1 entry", runProjection(h, "en").length === 1);
  // Oversized state (can only arise from a defect) is capped at three.
  const ten = Array.from({ length: 10 }, (_, i) => ({
    en: "N" + i, es: "S" + i, why: { en: "w", es: "ws" }, test: { en: "t", es: "ts" } }));
  check("a corrupt oversized state is capped at 3", runProjection(ten, "en").length === 3);
  check("a wiped state ships an empty array", runProjection(undefined, "en").length === 0);
}

// ===========================================================================
// 6. STATIC WIRING
// ===========================================================================
section("static wiring: markup, placement, wipe inventory, isolation");
check("the section markup exists with a class-free <ol>, statically empty",
  /<ol id="hf2Priorities" style="[^"]*"><\/ol>/.test(html)
  && !/<ol id="hf2Priorities"[^>]*class=/.test(html));
check("the section ships hidden and carries the existing pattern's classes only",
  /<section class="hf2-review-section" id="hf2PrioritiesSection" style="display:none">/.test(html));
check("placement: after 'What we set out to solve', above the finalists",
  html.indexOf('id="hf2NeedsLabel"') < html.indexOf('id="hf2PrioritiesSection"')
  && html.indexOf('id="hf2PrioritiesSection"') < html.indexOf('id="hf2FinalistsLabel"'));
check("no new component class: the section introduces no class outside the existing pattern",
  (() => {
    const m = html.match(/<section class="hf2-review-section" id="hf2PrioritiesSection"[\s\S]*?<\/section>/);
    if (!m) return false;
    const classes = [...m[0].matchAll(/class="([^"]+)"/g)].flatMap((c) => c[1].split(/\s+/));
    return classes.every((c) => ["hf2-review-section", "hf2-review-section__label"].includes(c));
  })());
check("the label is written by renderHf2's copy map, bilingually",
  /hf2PrioritiesLabel: es \? 'Lo que probaremos juntos' : 'What we will test together',/.test(html));
check("renderHf2 renders priorities between the brief and the picks",
  /renderHf2Brief\(\);\s*renderHf2Priorities\(\);\s*renderHf2Picks\(\);/.test(html));
check("the list is in the wipe's content inventory",
  /'hf2SleepSystemSection', 'hf2Priorities',/.test(html));
check("the section returns to hidden through SESSION_LAYERS",
  /\{ id: 'hf2PrioritiesSection', display: 'none' \},/.test(html));
check("the payload literal keeps the shape session_async pins ('};' at six spaces)",
  /const payload = \{[\s\S]*?\n      \};/.test(html));
check("the compute block never references financing",
  !/financing/i.test(PROFILE_FN));
check("the widened mapping stores no score, kind or rank",
  !/score|kind|rank/.test((PROFILE_FN.match(/analytics\.trialFocus = topPriorities\.map[\s\S]*?\}\);/) || [""])[0]));
// A source-shape complement to the per-fixture resultsTrialFocus pins above
// (which are the real behavioral coverage): the derivative still reads the
// store through L(item) rather than any new path.
check("renderResultsTrialFocus still reads the store through L(item)",
  /var focus = Array\.isArray\(analytics\.trialFocus\)\s*\? analytics\.trialFocus\.map\(function\(item\) \{ return L\(item\); \}\)\.filter\(Boolean\)/.test(TRIAL_FN));

// ===========================================================================
// 7. THE CTA RELABEL (owner-authorized 2026-08-10)
// ===========================================================================
// The Sleep Brief CTA hands off to the results reveal and always has — but its
// label used to claim "Compare My Matches", a comparison it never opened. The
// owner-ruled correction keeps the behavior and fixes the words. Three pins:
// the exact ruled pair as literals (on top of the fixture's cta fields, so
// neither a source revert nor a fixture regeneration can move the label
// alone), the unchanged handler wiring, and an honesty invariant coupling the
// two — while this control routes to Results, its label may not claim a
// comparison ("no first-visit Compare" is the controlling direction).
section("Sleep Brief CTA: ruled label, unchanged handler, honesty invariant");
{
  const enCta = runProfile(FIXTURES.A, "en").els.get("profileCta");
  const esCta = runProfile(FIXTURES.A, "es").els.get("profileCta");
  const enLabel = enCta.innerHTML || enCta.textContent;
  const esLabel = esCta.innerHTML || esCta.textContent;
  check("the EN label is exactly the ruled 'See My Matches →'",
    enLabel === "See My Matches →");
  check("the ES label is exactly the ruled provisional 'Ver Mis Opciones →'",
    esLabel === "Ver Mis Opciones →");
  const routesToResults =
    /<button class="noct-profile-cta" id="profileCta" onclick="window\.startResultsReveal\(\)" ontouchend="event\.preventDefault\(\);window\.startResultsReveal\(\);"><\/button>/
      .test(html);
  check("the CTA still routes to the results reveal via BOTH handlers, exactly",
    routesToResults);
  check("no comparison opener is wired to the CTA",
    !/id="profileCta"[^>]*(compareReviewFinalists|openCompareModal|toggleCompare)/.test(html));
  check("HONESTY: a results-routing CTA claims no comparison (EN)",
    !routesToResults || !/compar/i.test(enLabel));
  check("HONESTY: a results-routing CTA claims no comparison (ES)",
    !routesToResults || !/compar/i.test(esLabel));
}

// 2026-08-23 owner ruling (Slice 5 C10): the trial priorities are written
// BEFORE any finalist exists and are shown on the Sleep Plan in the
// no-finalist state beside "Recommended starting point / No finalist selected
// yet", so their prose may not call the mattress under test "the finalist".
// Three pins: the ruled wording as literals (on top of the fixture's test
// fields, so neither a source revert nor a fixture regeneration can move it
// alone), and a vocabulary invariant over every priority the engine emits.
section("trial priorities: ruled neutral wording, no 'finalist' vocabulary");
{
  const EN_RULED = "Try the mattress flat, then with the head gently raised on an adjustable base.";
  const ES_RULED = "Prueba el colchón plano y luego con la cabeza ligeramente elevada en una base ajustable.";
  const elevEn = runProfile(FIXTURES.C, "en").analytics.trialFocus.find((t) => t.en === "Comfortable elevation");
  const elevEs = runProfile(FIXTURES.C, "es").analytics.trialFocus.find((t) => t.en === "Comfortable elevation");
  check("the 'Comfortable elevation' testing prose is exactly the ruled EN wording",
    !!elevEn && elevEn.test.en === EN_RULED);
  check("...and exactly the ruled provisional ES wording",
    !!elevEs && elevEs.test.es === ES_RULED);
  check("the fixture carries the ruled wording too (source and oracle agree independently)",
    BASELINE.C.en.priorities.some((p) => p.test === EN_RULED) && BASELINE.C.es.priorities.some((p) => p.test === ES_RULED));
  check("the retired wording is gone from the producer source", !/the finalist flat/.test(html) && !/el finalista plano/.test(html));
  let violations = [];
  for (const f of Object.keys(FIXTURES)) {
    for (const lang of ["en", "es"]) {
      for (const t of runProfile(FIXTURES[f], lang).analytics.trialFocus) {
        for (const s of [t.en, t.es, t.why && t.why.en, t.why && t.why.es, t.test && t.test.en, t.test && t.test.es]) {
          if (typeof s === "string" && /\bfinalist(a|as|s)?\b/i.test(s)) violations.push(`${f}/${lang}: ${s}`);
        }
      }
    }
  }
  check("VOCABULARY: no emitted priority name, reason or testing prose calls the mattress 'the finalist' (EN or ES), across every fixture",
    violations.length === 0, violations.join(" | "));
}

// ===========================================================================
// Slice 5 C1: the completeness predicate is INLINED in both the producer
// (showProfileScreen) and the consumer (renderHf2Priorities) because four
// suites extract those functions by regex. Inlining is only safe if the two
// copies are byte-identical, so that is pinned here.
{
  const copies = [...html.matchAll(/      var trialFocusIsComplete = function\(stored\) \{[\s\S]*?\r?\n      \};\r?\n/g)].map((m) => m[0].replace(/\r\n/g, "\n"));
  check(`the all-or-nothing completeness predicate is inlined exactly twice (producer + consumer), found ${copies.length}`, copies.length === 2);
  check("the two inlined copies are byte-identical (no drift between producer and consumer)",
    copies.length === 2 && copies[0] === copies[1]);
  check("the predicate requires BOTH languages for name, why and test (completeness is language-independent)",
    copies.length === 2 && /str\(item\.en\) && str\(item\.es\)/.test(copies[0])
    && /str\(item\.why\.en\) && str\(item\.why\.es\)/.test(copies[0])
    && /str\(item\.test\.en\) && str\(item\.test\.es\)/.test(copies[0]));
  check("the consumer no longer filters per element (no `var valid = stored.filter(`)",
    !/var valid = stored\.filter\(/.test(html));
  check("the producer stores the built array only when complete, else []",
    /analytics\.trialFocus = trialFocusIsComplete\(builtTrialFocus\) \? builtTrialFocus : \[\];/.test(html));
  // The EMAIL projection keeps its pre-existing per-entry filter — deferred
  // §1.6 work by owner ruling. Pinned so nobody "fixes" it here silently.
  check("[deferred §1.6] the email projection's per-entry filter is untouched by this slice",
    /priorities: \(Array\.isArray\(analytics\.trialFocus\) \? analytics\.trialFocus : \[\]\)/.test(html));
}

console.log(`\nConsultation priorities check: ${passed} passed, ${failed} failed`);
process.exit(failed === 0 ? 0 : 1);
